### PR TITLE
Hello Microverse Project

### PR DESCRIPTION
**Pull request by Kamba56**
Added index.html file.
Added style.css file.
Added linters.

### CODE REVIEW

**Review by prolajumokeoni — CHANGES_REQUESTED** [review]
Hi @Kamba56 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️ Good commit messages


## Required Changes ♻️

- [ ] Kindly make your pull request title to be a descriptive title that refers to changes in your pr.



_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Naming your branch a feature name in your project e.g "hello-microverse"

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kamba56** [comment]
Hello @prolajumokeoni 
Please I don't understand what is wrong. Can you explain please.

**Comment by prolajumokeoni** [comment]
> Hello @prolajumokeoni 
> Please I don't understand what is wrong. Can you explain please.

Kindly edit pull request title to be more descriptive, check how to do it here ⬇️
https://bitbucket.org/blog/editing-pull-requests-just-got-a-little-easier#:~:text=The%20current%20way%20to%20update,pull%20request%20has%20been%20merged.

**Review by KayLemba — APPROVED** [review]
Hi @Kamba56 

Good job,
Congratulations  your project has been approved . There is nothing more to say than its time to merge your work. 🥇  Keep  up the good work.

## Highlights
- App is working as intended
- No linter errors 
- Descriptive Pull Request

## Required Changes ♻️
N/A

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O

**Pull request merged**
